# Introducing Pandas Objects

At the very basic level, Pandas objects can be thought of as **enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.**
As we will see during the course of this chapter, Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but **nearly everything that follows will require an understanding of what these structures are**.
Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the ``Series``, ``DataFrame``, and ``Index``.

We will start our code sessions with the standard NumPy and Pandas imports:

In [2]:
import numpy as np
import pandas as pd

## The Pandas Series Object

A Pandas ``Series`` is a one-dimensional array of indexed data.
It can be created from a list or array as follows:

In [3]:
# Heights of class
data = pd.Series([1.5, 1.6, 1.75, 1.8])
data

0    1.50
1    1.60
2    1.75
3    1.80
dtype: float64

In [4]:
data.values # así se ve el numpy que hay dentro

array([1.5 , 1.6 , 1.75, 1.8 ])

In [5]:
data.values

array([1.5 , 1.6 , 1.75, 1.8 ])

As we see in the output, the ``Series`` wraps both a sequence of values and a sequence of indices, which we can access with the ``values`` and ``index`` attributes.
The ``values`` are simply a familiar NumPy array:

In [6]:
#Se ha creado un pandas de tipo serie, a partir de una lista NumPy.
data = pd.Series([1.5, 1.6, 1.75, 1.8, "hola"])
data

0     1.5
1     1.6
2    1.75
3     1.8
4    hola
dtype: object

In [7]:
#Se puede sumar valores de dentro del NumPy array. Sin reescribir el array.
data[0] + data[1]

3.1

In [8]:
#Te describe el array 
data.values

array([1.5, 1.6, 1.75, 1.8, 'hola'], dtype=object)

The ``index`` is an array-like object of type ``pd.Index``, which we'll discuss in more detail momentarily.

In [10]:

type(data)

pandas.Series

In [11]:
#index es un objeto similar a un array, de tipo pd.Index
#Es lo ismo que range(0, 5, 1)
data.index

RangeIndex(start=0, stop=5, step=1)

Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [13]:
#Acceso al valor de un indice en concreto, es igual que cuando lo hacemos con Python 
data[0]

1.5

In [14]:
type(data.values[0])

float

In [16]:
#Filtrado por slicing, igual que en listas, arrays de NumPy y tuplas
data[1:3]

1     1.6
2    1.75
dtype: object

In [17]:
#Filtrado por slicing, para colocarlo al reves
data[-1::-1]#[0]

4    hola
3     1.8
2    1.75
1     1.6
0     1.5
dtype: object

As we will see, though, **the Pandas ``Series`` is much more general and flexible than the one-dimensional NumPy** array that it emulates.

la Series de Pandas no solo **guarda valores y etiquetas/índices**.
1. NumPy array -> valores + posición
2. Pandas Series -> valores + índice/etiquetas

### ``Series`` as generalized NumPy array

From what we've seen so far, it may look like the ``Series`` object is basically interchangeable with a one-dimensional NumPy array.
**The essential difference is the presence of the index**: while the Numpy Array has an *implicitly defined* integer index used to access the values, the Pandas ``Series`` has an ***explicitly defined*** index associated with the values.

This explicit index definition gives the ``Series`` object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.
For example, **if we wish, we can use strings as an index:**

In [18]:
data = pd.Series([1.5, 1.6, 1.75, 1.80], 
                 index=['Jane', 'Joe', 'Susan', 'Mike'])
data

Jane     1.50
Joe      1.60
Susan    1.75
Mike     1.80
dtype: float64

In [19]:
data['Jane']

np.float64(1.5)

In [20]:
data.index

Index(['Jane', 'Joe', 'Susan', 'Mike'], dtype='str')

In [21]:
data

Jane     1.50
Joe      1.60
Susan    1.75
Mike     1.80
dtype: float64

In [22]:
data["Joe":"Mike"]

Joe      1.60
Susan    1.75
Mike     1.80
dtype: float64

In [23]:
data["Joe":"Mike":-1]

Series([], dtype: float64)

In [24]:
data["Mike":"Joe"]

Series([], dtype: float64)

In [25]:
data

Jane     1.50
Joe      1.60
Susan    1.75
Mike     1.80
dtype: float64

In [26]:
data[-1:0:-1]

Mike     1.80
Susan    1.75
Joe      1.60
dtype: float64

In [27]:
test = pd.Series([1,2,3,4,5,6], index = ["Alberto", "Joe", "Mary", "Joe", "Peter", "Joe"])
test

Alberto    1
Joe        2
Mary       3
Joe        4
Peter      5
Joe        6
dtype: int64

In [28]:
#test["Alberto":"Joe"] # no puedes hacer slicing para índices no únicos
test["Joe"]

Joe    2
Joe    4
Joe    6
dtype: int64

In [29]:
data[1:3]

Joe      1.60
Susan    1.75
dtype: float64

And the item access works as expected:

In [30]:
data['Susan']

print(data['Susan'])
#Acceso por posición
print(data.iloc[2])
#Slicing por posición: el final NO se incluye
print(data.iloc[0:2])
#Slicing por etiquetas: la etiqueta final SÍ se incluye
print(data['Jane':'Susan'])

1.75
1.75
Jane    1.5
Joe     1.6
dtype: float64
Jane     1.50
Joe      1.60
Susan    1.75
dtype: float64

We can even use non-contiguous or non-sequential indices:

In [31]:
data = pd.Series([1.5, 1.6, 1.75, 1.80],
                 index=[2, 5, 3, 7])
data

2    1.50
5    1.60
3    1.75
7    1.80
dtype: float64

In [32]:
data[2:5]

3    1.75
7    1.80
dtype: float64

### Series as specialized dictionary

In this way, you can think of a **Pandas ``Series`` a bit like a specialization of a Python dictionary.**
A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a ``Series`` is a structure which maps typed keys to a set of typed values.
This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas ``Series`` makes it much more efficient than Python dictionaries for certain operations.

The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [33]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

#Transforma un diccionario Python a una Serie Pandas con pd.Series
#Donde la palabras clave de los diccionarios serán los indices de la Serie de Pandas, y los valores del diccionario los valores de la Serie
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

By default, a ``Series`` will be created where the index is drawn from the sorted keys.
From here, typical dictionary-style item access can be performed:

In [34]:
population['California']

np.int64(38332521)

Unlike a dictionary, though, the ``Series`` also supports array-style operations such as slicing:

In [35]:
#slicing por etiquetas
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

We'll discuss some of the quirks of Pandas indexing and slicing in [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb).

### Constructing Series objects

We've already seen a few ways of constructing a Pandas ``Series`` from scratch; all of them are some version of the following:

```python
>>> pd.Series(data, index=index)
```

where ``index`` is an optional argument, and ``data`` can be one of many entities.

For example, ``data`` can be a list or NumPy array, in which case ``index`` defaults to an integer sequence:

In [36]:
pd.Series([2,3,6])

0    2
1    3
2    6
dtype: int64

``data`` can be a scalar, which is repeated to fill the specified index:

In [37]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

``data`` can be a dictionary, in which ``index`` defaults to the sorted dictionary keys:

In [38]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: str

In each case, the index can be explicitly set if a different result is preferred:

In [42]:
#defines la serie Pandas con un diccionario
#con solo las claves 3 y 2 con el orden indicado 
p = pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])
p

3    c
2    a
dtype: str

In [43]:
p = pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2,1])
print(p)
#Filtra las dos primeras posiciones (0-1) 
#Busca la etiqueta 2 dentro de ese resultado
p[0:2][2]

3    c
2    a
1    b
dtype: str

'a'

Notice that in this case, the ``Series`` is populated only with the explicitly identified keys.

## The Pandas DataFrame Object

The next fundamental structure in Pandas is the ``DataFrame``.
Like the ``Series`` object discussed in the previous section, the ``DataFrame`` can be **thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.**
We'll now take a look at each of these perspectives.

### El objeto DataFrame de Pandas
La siguiente estructura fundamental de Pandas es el DataFrame.
Al igual que el objeto Series que vimos antes, un DataFrame puede entenderse de dos maneras:
- **generalización de un array de NumPy**
- **especialización de un diccionario de Python**

### DataFrame as a generalized NumPy array
If a ``Series`` is an analog of a one-dimensional array with flexible indices, a **``DataFrame`` is an analog of a two-dimensional array with both flexible row indices and flexible column names.**
Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a ``DataFrame`` as a sequence of aligned ``Series`` objects.
Here, by "aligned" we mean that **they share the same index.**

To demonstrate this, let's first construct a new ``Series`` listing the area of each of the five states discussed in the previous section:

Si **una Series es parecida a un array de una dimensión con índices flexibles**, **un DataFrame es parecido a un array de dos dimensiones*con índices y nombres flexibles.

También puedes pensar en un **DataFrame como una secuencia de varias Series alineadas**.

Aquí, cuando dice que están alineadas, significa que **comparten el mismo índice**.

In [44]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

Now that we have this along with the ``population`` Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [45]:
# Con las Series ya creadas de population y area, se crea un DataFrame.
# population y area serán las columnas, mientras que los estados serán los índices de las filas.
states = pd.DataFrame({'population': population,
                       'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [46]:
type(states)

pandas.DataFrame

In [47]:
# .values devuelve los valores del DataFrame como un array de NumPy.
# No incluye ni los índices de las filas ni los nombres de las columnas.
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

Like the ``Series`` object, the ``DataFrame`` has an ``index`` attribute that gives access to the index labels:

In [49]:
#atributo index que permite acceder a las etiquetas de los índices
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')

Additionally, the ``DataFrame`` has a ``columns`` attribute, which is an ``Index`` object holding the column labels:

In [50]:
# Selecciona nombres de columnas mediante slicing
states.columns[:1]

Index(['population'], dtype='str')

In [51]:
# Muestra las primeras 3 filas del DataFrame
states.head(3)

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [52]:
#Crea un DataFrame vacio
midf = pd.DataFrame()
#Crea una nueva columna llamada temperatura con los valores 1, 2, 3
#Como no se indica los indices, Pandas los creaautomaticamente
midf['temperatura'] = [1,2,3]
midf

   temperatura
0            1
1            2
2            3

**Thus the ``DataFrame`` can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.**

**Por tanto, un DataFrame puede entenderse como una generalización de un array bidimensional de NumPy, donde tanto las filas como las columnas tienen índices flexibles que permiten acceder a los datos.**

### DataFrame as specialized dictionary

Similarly, we can also think of a ``DataFrame`` as a specialization of a dictionary.
Where a dictionary maps a key to a value, a ``DataFrame`` maps a column name to a ``Series`` of column data.
For example, asking for the ``'area'`` attribute returns the ``Series`` object containing the areas we saw earlier:

**un DataFrame relaciona el nombre de una columna con una Series que contiene los datos de esa columna.**

In [53]:
# Un DataFrame se puede entender como un diccionario:
# nombre_columna -> Series

# Devuelve la columna 'population' como una Series
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [54]:
# Devuelve el nombre de la Series/columna

states['area'].name

'area'

**un DataFrame puede verse como varias Series agrupadas bajo distintos nombres de columna.**

**Notice the potential point of confusion here: in a two-dimesnional NumPy array, ``data[0]`` will return the first *row*. For a ``DataFrame``, ``data['col0']`` will return the first *column*.**
Because of this, it is probably better to think about ``DataFrame``s as generalized dictionaries rather than generalized arrays, though both ways of looking at the situation can be useful.
We'll explore more flexible means of indexing ``DataFrame``s in [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb).

In [ ]:
# Ojo con la diferencia entre NumPy y Pandas:

# NumPy 2D:
# array[0] devuelve la primera fila.

# Pandas DataFrame:
# df['columna'] devuelve una columna como Series.

# Por eso un DataFrame se puede entender mejor
# como un diccionario:
# nombre_columna -> Series

### Constructing DataFrame objects

A Pandas ``DataFrame`` can be constructed in a variety of ways.
Here we'll give several examples.

#### From a single Series object

A ``DataFrame`` is a collection of ``Series`` objects, and a single-column ``DataFrame`` can be constructed from a single ``Series``:

Un DataFrame es una colección de objetos Series, y un DataFrame de una sola columna puede construirse a partir de una única Series.

In [55]:

# Podemos crear un DataFrame de una sola columna a partir de una Series
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [56]:
# Convierte la Series population en un DataFrame de una columna
# y después selecciona esa columna, devolviendo de nuevo una Series.
pd.DataFrame(population, columns=['population'])['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [57]:
## Otra forma de acceder a una columna
states.area

#suele ser mejor usar: states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

#### From a list of dicts

Any list of dictionaries can be made into a ``DataFrame``.
We'll use a simple list comprehension to create some data:

In [78]:

# LIST COMPREHENSION
# Creamos una lista de diccionarios mediante list comprehension.
# Cada diccionario se convertirá posteriormente en una fila del DataFrame.
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)
# [{'a':0, 'b':0}, {'a':1, 'b':2}, {'a':2, 'b':4}]

   a  b
0  0  0
1  1  2
2  2  4

In [79]:
# DICT COMPREHENSION
# Forma compacta de crear un diccionario
{x: x*2 for x in [1, 2, 3]}

{1: 2, 2: 4, 3: 6}

In [80]:
# List comprehension con condición:
# Si x es 1 o 2, se añade x*2.
# En caso contrario, se añade 10.
[    x*2  if x ==2 or x == 1 else 10  for x  in [1,2,3]    ]  # list comprehension

[2, 4, 10]

In [62]:
# Forma tradicional: crear una lista y añadir valores con append()
l = []
for x in [1,2,3]:
    l.append(x*2)
l

[2, 4, 6]

In [63]:
# List comprehension:
# crea una nueva lista aplicando x + 1 a cada elemento
[   x+1  for x in [1,2,3,9] ]

[2, 3, 4, 10]

In [64]:
# Dict comprehension:
# x será la clave y "letra: " + x será el valor
{x: "letra: " + x for x in ['a','b','c']} # dict comprehesion

{'a': 'letra: a', 'b': 'letra: b', 'c': 'letra: c'}

Even if some keys in the dictionary are missing, Pandas will fill them in with ``NaN`` (i.e., "not a number") values:

In [82]:
import pandas as pd
import numpy as np

midic1 = {'a': 1, 'b': 2}
midic2 = {'b': 3, 'c': 4}

# Cada diccionario se convierte en una fila.
# Las claves se convierten en columnas.
# Si falta una clave, Pandas rellena ese valor con NaN.
midf = pd.DataFrame(data = [midic1, midic2])

# Cambiamos los índices de las filas
midf.index = ["hola", "adiós"]
midf

         a  b    c
hola   1.0  2  NaN
adiós  NaN  3  4.0

lista de diccionarios -> DataFrame

- Cada diccionario -> fila
- Cada clave -> columna
- Clave inexistente -> NaN

Aquí estás viendo tres ideas distintas:**los tipos de datos de cada columna (dtypes), el tipo de un valor concreto, y cómo acceder a una posición concreta del array subyacente.**

In [ ]:
# Creamos un DataFrame a partir de una lista de diccionarios.
# Cada diccionario representa una fila y cada clave representa una columna.
# Si alguna clave falta en una fila, Pandas rellenará ese valor con NaN.
pd.DataFrame([{'a': "hola", 'b': 2}, { 'a': 1, 'b': 3, 'c': 4}]).dtypes

a     object
b      int64
c    float64
dtype: object

In [ ]:
# .values devuelve los datos del DataFrame como un array de NumPy.
# [1][0] accede a la segunda fila y a la primera columna.
type(pd.DataFrame([{'a': "hola", 'b': 2},
                   { 'a': 1, 'b': 3, 'c': 4}])
     .values[1][0])

int

In [ ]:
# .values devuelve los datos del DataFrame como un array.
# [0][1] accede a la primera fila y a la segunda columna.
pd.DataFrame([{'a': "hola", 'b': 2},
                   { 'a': 1, 'b': 3, 'c': 4}])\
     .values[0][1]

2

In [ ]:
# IMPORTANTE:
# En los índices numéricos se empieza a contar desde 0.
# [fila][columna]

# [1][0] -> segunda fila, primera columna
# [0][1] -> primera fila, segunda columna

In [87]:
# Accedemos por posición:
# fila 1 = segunda fila
# columna 0 = primera columna
midf.iloc[1, 0]

np.float64(nan)

In [ ]:
# .dtypes -> tipos de las columnas
# .values -> valores como array de NumPy
# .iloc[fila, columna] -> acceso por posición

In [ ]:
# \n crea un salto de línea dentro de un string.
# Las triples comillas permiten escribir strings en varias líneas.
# Si escribimos dos strings seguidos sin coma ni operador,
# Python los concatena automáticamente.

print("lalala\nlelele"
"""lalala\nlelele
lololo""")

lalala
lelelelalala
lelele
lololo

In [ ]:
# .values convierte el DataFrame en un array.
# [1][0] accede a la segunda fila y primera columna.
# type() comprueba el tipo del valor obtenido.
type(pd.DataFrame([{'a': "hola", 'b': 2},
                   { 'a': 1, 'b': 3, 'c': 4}]).values[1][0])

int

In [ ]:
# dtype muestra el tipo de dato almacenado en el array de NumPy.
np.array([5]).dtype

dtype('int64')

In [ ]:
# Accedemos al primer elemento del array.
# Como pertenece a NumPy, su tipo es numpy.int64.
type(np.array([5])[0])

numpy.int64

In [ ]:
# La barra invertida \ al final de una línea
# permite continuar el código/string en la siguiente línea
# sin añadir un salto de línea.
print(
 "hola\
 qué\
 tal" 
)

hola qué tal

In [74]:
# 1.8   1.80  1.8000000000000001
# 8   8.

In [ ]:
# np.inf representa infinito positivo.
np.inf

inf

In [ ]:
# Otra forma de representar infinito positivo usando Python.
float('inf')

inf

In [ ]:
# np.nan representa un valor ausente o no definido.
np.nan

nan

- np.inf  -> infinito
- np.nan  -> dato ausente / no válido

#### From a dictionary of Series objects

As we saw before, a ``DataFrame`` can be constructed from a dictionary of ``Series`` objects as well:

In [ ]:
#Crea un DataFrame a partir de un diccionario
pd.DataFrame({'population': population,
              'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### From a two-dimensional NumPy array

Given a two-dimensional array of data, we can create a ``DataFrame`` with any specified column and index names.
If omitted, an integer index will be used for each:

In [ ]:
# Creamos un DataFrame a partir de un array 2D de NumPy.
# np.random.rand(3, 2) genera 3 filas y 2 columnas
# con valores aleatorios entre 0 y 1.
# columns define los nombres de las columnas.
# index define las etiquetas de las filas.

pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.463872  0.429255
b  0.273549  0.218432
c  0.323861  0.519358

#### From a NumPy structured array

We covered structured arrays in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).
A Pandas ``DataFrame`` operates much like a structured array, and can be created directly from one:

In [ ]:
# Creamos un array estructurado de NumPy con 3 registros.
# Cada registro tiene tres campos:
# A -> entero int64
# B -> float64
# C -> float64
# np.zeros inicializa todos los valores a 0.

import numpy as np
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8'), ('C', 'f8')])
A

array([(0, 0., 0.), (0, 0., 0.), (0, 0., 0.)],
      dtype=[('A', '<i8'), ('B', '<f8'), ('C', '<f8')])

In [ ]:
# Convertimos directamente el array estructurado
# en un DataFrame.
# Los nombres de los campos pasan a ser las columnas.

pd.DataFrame(A)

   A    B    C
0  0  0.0  0.0
1  0  0.0  0.0
2  0  0.0  0.0

## The Pandas Index Object

We have seen here that both the ``Series`` and ``DataFrame`` objects contain an explicit *index* that lets you reference and modify data.
This ``Index`` object is an interesting structure in itself, and **it can be thought of either as an *immutable array* or as an *ordered set* (technically a multi-set, as ``Index`` objects may contain repeated values).**
Those views have some interesting consequences in the operations available on ``Index`` objects.
As a simple example, let's construct an ``Index`` from a list of integers:

In [ ]:
# Creamos un objeto Index de Pandas a partir de una lista.
# Un Index contiene las etiquetas utilizadas para identificar
# filas o elementos en Series y DataFrame.
# Es una estructura ordenada e inmutable.

ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

The ``Index`` in many ways operates like an array.
For example, we can use standard Python indexing notation to retrieve values or slices:

In [ ]:
#Acceder a la segunda posición
ind[1]

np.int64(3)

In [ ]:
# Slicing del Index de 2 en 2.
ind[::2]

Index([2, 5, 11], dtype='int64')

``Index`` objects also have many of the attributes familiar from NumPy arrays:

In [ ]:
# shape -> forma del Index
# ndim -> número de dimensiones
# dtype -> tipo de dato de sus elementos
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

One difference between ``Index`` objects and NumPy arrays is that indices are immutable–that is, they cannot be modified via the normal means:

In [ ]:
#Da error porque el Index es inmutable.
ind[1] = 0

TypeError: Index does not support mutable operations

**This immutability makes it safer to share indices between multiple ``DataFrame``s and arrays, without the potential for side effects from inadvertent index modification.**

### Index as ordered set

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic.
**The ``Index`` object follows many of the conventions used by Python's built-in ``set`` data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way:**

In [101]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [ ]:
# intersection() devuelve los elementos comunes
# entre los dos índices.
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [104]:
indA.intersection(indB)
indA.__and__(indB) # indA & indB

Index([0, 3, 5, 7, 9], dtype='int64')

In [105]:
indA | indB  # union

Index([3, 3, 5, 7, 11], dtype='int64')

In [ ]:
# Unión: todos los elementos sin repetir
testindA = pd.Index([1,2,3,3,3,3,3,3])
testindB = pd.Index([2,3,1,5, 5, 1])
testindA.union(testindB)

Index([1, 1, 2, 3, 3, 3, 3, 3, 3, 5, 5], dtype='int64')

In [107]:
indA ^ indB  # symmetric difference

Index([3, 0, 0, 0, 2], dtype='int64')

These operations may also be accessed via object methods, for example ``indA.intersection(indB)``.

In [ ]:
# Operaciones de conjuntos con objetos Index

# Intersección: elementos comunes
indA.intersection(indB)

# Unión: todos los elementos sin repetir
indA.union(indB)

# Diferencia: elementos de indA que no están en indB
indA.difference(indB)

# Diferencia simétrica:
# elementos que están en uno u otro, pero no en ambos
indA.symmetric_difference(indB)


# IMPORTANTE:
# En versiones actuales de Pandas es preferible usar
# intersection(), union(), difference(), etc.
# y no operadores como &, | o /,
# porque pueden realizar operaciones elemento a elemento.